export { default as Hero } from './Hero'
export { default as OurReach } from './OurReach'
export { default as OurSolution } from './OurSolution'
export { default as Testimonials } from './Testimonials'
export { default as OurCollaborations } from './OurCollaborations'
export { default as AboutUs } from './AboutUs'